version: "3"

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    user: 0:0
    privileged: true
    restart: always
    ports:
      - "80:8080"
      - "5005:5005"
    volumes:
      - ${HOME}/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

volumes:
  jenkins:
    driver: local