logging:
  level:
    com:
      solvd:
        ikaravai: INFO
    org:
      springframework:
        data: INFO
server:
  port: 8090
spring:
  data:
    mongodb:
      uri: mongodb://${USER_NAME}:${USER_PASSWORD}@${DB_URL}:27017/user-ms?authSource=admin
      authentication-database: admin
      auto-index-creation: true
