spring:
  application:
    name: USER_MICROSERVICE
  data:
    mongodb:
      #host: localhost
      #port: 27017
      #username: myuser
      #username: ${MONGODB_ROOT_USERNAME}
      #password: mypass
      #password: ${MONGODB_ROOT_PASSWORD}
      #database: ${MONGODB_NAME}
      #database: user-ms
      uri: mongodb://user:password@mongodb:27017/user-ms?authSource=admin
      authentication-database: admin
      auto-index-creation: true

logging:
  level:
    com:
      solvd:
        ikaravai: INFO
    org:
      springframework:
        data: INFO
server:
  #port: ${USERMS_PORT}
  port: 8090
  #address: 0.0.0.0
