services:
  microservicestudy:
    image: example.com/library/microservicestudy:latest
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "microservicestudy"
networks:
  backend:
    driver: bridge
