server:
  port: 9000

spring:
  r2dbc:
    url: r2dbc:postgresql://db:5432/user_db
    username: postgres
    password: postgres
  sql:
    init:
      data-locations: sql/schema.sql

logging:
  level:
    org.springframework.r2dbc: DEBUG