spring:
  application:
    name: config-server
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        vault:
          port: 8200
          host: 127.0.0.1
          kv-version: 2
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/pstakhiyevich/config.git
          search-paths: licenseservice
server:
  port: 8071

encrypt:
  key: secretKey