apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ms-deployment
  labels:
    app: user-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-ms
  template:
    metadata:
      labels:
        app: user-ms
    spec:
      containers:
        - name: user-ms
          image: ikaravai/jbogor:1.1
          ports:
            - containerPort: 8090
          env:
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-user
          - name: USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-password
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: user-ms-service
spec:
  type: NodePort
  selector:
    app: user-ms
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 31000