version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - user
  user-service:
      image: micro.org/library/user-crud:latest
      restart: always
      ports:
        - '9000:9000'
      networks:
        - user

volumes:
  db:
    driver: local
networks:
  user: